### ISSUE TITLE
URL generation is using the wrong hostname on dedicated worker services.

### ISSUE THREAD

**Issue by michaijtsma** [tradecoverexchange/google-cloud-tasks-laravel#2]
I'm using this package to handle my push queue on an App Engine Application. The default service on App Engine is serving requests and generating the tasks for the queue (eg: `https://default-dot-myappengineproject.appspot.com`).

The queue is being processed on a dedicated service (eg: `https://queueworker-dot-myappengineproject.appspot.com`). 

Everything is working fine except for the url generation:
The urls the are being generated by the URL helper (and used in my emails) are based on the current host which now is `https://queueworker-dot-myappengineproject.appspot.com` because the task is handled on my dedicated service.

Ideally the task generator should fetch the current host when creating the task and pass that as a parameter to the queue handler so the queue handler can force the current host with: `URL::forceRootUrl($parameter_from_task_generator)`

**Comment by peterfox** [comment]
Ok, I think I understand the issue but will need a bit of time to consider what's the best resolution as I could see people wanting multiple services so ideally.

**Comment by peterfox** [comment]
@vigiland I think I know what the problem is and it's a bit of an edge case but I can understand the issue. Can you confirm firstly that your APP_URL env is set to `https://default-dot-myappengineproject.appspot.com` and that you are using the `'driver' => 'google_app_engine_cloud_tasks',` driver type in your queue config?

**Comment by peterfox** [comment]
This issue should be fixed now as of 0.4.0. You just need to ensure that your app.url value in the config, normally set by the APP_URL env is set to the frontend you want it to go to.
